### ISSUE TITLE
Intermediate jet containers

### ISSUE THREAD

**Issue by AvivCukierman** [kratsg/JetReclustering#14]
Intermediate jet containers sometimes have the same names if the input containers were the same

**Comment by kratsg** [comment]
It turns out they don't! https://github.com/kratsg/xAODJetReclustering/blob/master/Root/JetReclusteringTool.cxx#L55-L57

```
  // this is for intermediate output containers used between tools
  std::string filteredInputJetContainer = m_inputJetContainer+"_"+m_name+"_FilteredPtMin_"+std::to_string(static_cast<int>(m_ptMin_input));
  std::string filteredInputPseudoJetsContainer = "PseudoJets_"+filteredInputJetContainer;
```

`m_name` is the name of the tool. So it will be made unique to the xJRTool itself.
